# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MavenProject Build
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    outputs:
      jar_version: ${{ steps.bump.outputs.jar_version }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Bump jar version
      id: bump
      run: |
        POMPATH=myapp
        OLD_VERSION=$(cd $POMPATH && mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        BUMP_MODE="none"
        old="$OLD_VERSION"
        parts=( ${old//./ } )
        bv=$((parts[2] + 1))
        NEW_VERSION="${parts[0]}.${parts[1]}.${bv}"
        echo "pom.xml at" $POMPATH "will be bumped from" $OLD_VERSION "to" $NEW_VERSION
        mvn -q versions:set -DnewVersion="${NEW_VERSION}" --file $POMPATH/pom.xml
        echo ::set-output name=jar_version::${NEW_VERSION}
    #- name: Compile
      #run: mvn -B compile --file myapp/pom.xml

    #- name: Build a package
     # run: mvn -B package --file myapp/pom.xml

    - name: Temporarily save jar artifact
      uses: actions/upload-artifact@v2
      with:
        name: jar-artifact
        path: ${{ github.workspace }}/myapp/target/*.jar
        retention-days: 1
    - name: Docker build
      id: build
      working-directory: ./
      run: |
         docker build --no-cache --build-arg POM=${{steps.bump.outputs.jar_version}} -t zoharperets/maven-proj:${{steps.bump.outputs.jar_version}} .
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: zoharperets
        password: zp66152433!
    - name: Docker push
      run: |
        docker push zoharperets/maven-proj -a
    - name: Pull Docker image
      uses: docker/pull-action@v2
      with:
        args: zoharperets/maven-proj:${{steps.bump.outputs.jar_version}}  
    - name: Run Docker image
      uses: docker/run-action@v1
      with:
        args: sh -c "echo Hello from Docker!"
    - name: push to github
      run: |
       git config --global user.email "zoharperets92@gmail.com"
       git config --global user.name "zoharperetz"
       git add ./myapp/pom.xml
       git commit -m "update pm"
       git push
